language: node_js
node_js:
  - 0.8
before_script:
  - wget https://github.com/n1k0/casperjs/archive/1.0.2.tar.gz
  - tar -xf 1.0.2.tar.gz
  - sudo ln -s `pwd`/casperjs-1.0.2/bin/casperjs /usr/local/bin/casperjs
  - phantomjs --version
  - casperjs --version
script:
  - casperjs test --includes=unit_tests/caspersetup.js --fail-fast --direct unit_tests/tests/